### ISSUE TITLE
Section headings

### ISSUE THREAD

**Issue by mbellitti** [mtn/cocoa-eh-hugo-theme#116]
I'm trying to create a section that contains a list of posts and an header. 
I followed the instructions in the wiki (about [Sections](https://github.com/mtn/cocoa-eh-hugo-theme/wiki/Sections)) but the header file keeps showing up as an article.

For example, I created a section `books` that contains the file `books.md`, and now I see this
![image](https://user-images.githubusercontent.com/5868852/51476086-7214cb80-1d52-11e9-9217-19a2e100057f.png)
instead of the content of books.md as the section heading.

**Comment by mtn** [comment]
Hm, I believe the wiki needs to be updated. I'll double check as soon as I get a chance, update it if necessary, and let you know.

**Comment by mtn** [comment]
Okay, I thought I remembered it working this way, but looking at the implementation and back in history I'm not sure how it ever worked that way. It's easy to implement though, and I don't think there's support for adding annotations except on the main home page, so I'll add it.

**Comment by mtn** [comment]
@mbellitti I implemented this on the `dev` branch. Could you let me know if you have any thoughts?

One thing that differs from the standard home page description is I put the description after the section heading, since that seemed better.

![Screen Shot 2019-04-06 at 3 28 23 PM](https://user-images.githubusercontent.com/4515110/55674920-a2afd000-5880-11e9-83ef-9aba834d2696.png)

That content comes form `content/books/books.md`.
