### ISSUE TITLE
Unexpected behavior of sections

### ISSUE THREAD

**Issue by niklasfyi** [mtn/cocoa-eh-hugo-theme#124]
Hi,

first of all: THANKS! Greate theme.

I am just testing the example page and have something strange in my projects list

![DateTheme](https://user-images.githubusercontent.com/9086371/58815347-b761d780-8627-11e9-8efa-9f40b260a2e1.png)

The second date is the one from content/projects/projects.md. But the content of this file should only be for information and shouldn't be inside the list

**Comment by mtn** [comment]
Okay, I'm pretty sure I know what's going on. Is there anywhere I can see the source that generates this?

**Comment by niklasfyi** [comment]
It was just a cp -r exampleSite/* into my new Hugo Site. I did not change anything

**Comment by mtn** [comment]
Ok thanks. I'll probably be slow to resolve this since I'm really busy over the next week and a half, but if you or anyone else want to take a shot at it the fix should go around [here](https://github.com/mtn/cocoa-eh-hugo-theme/blob/915f2000ffc7a2db7b6d053ac7b626138d3248b1/layouts/_default/section.html#L16). We just need to not render a section when the only post there has the same title as the section.

**Comment by vighneshq** [comment]
@mtn Made a [pull request](https://github.com/mtn/cocoa-eh-hugo-theme/pull/125) regarding this. Can you take a look?

**Comment by v-shenoy** [comment]
@mtn Submitted a fix to this issue. Can you have a look, and check if it is alright?

**Comment by mtn** [comment]
Thanks @vighneshq!

**Comment by v-shenoy** [comment]
Thanks to you for such a great theme, just trying to give something back!
