### ISSUE TITLE
Using progressive image loading breaks images in RSS file

### ISSUE THREAD

**Issue by keanemind** [mtn/cocoa-eh-hugo-theme#17]
If I'm using progressive image loading, I link to img/picture.png in my content files. However, the image is actually stored in img/high/picture.png and img/low/picture.png. The problem is that Hugo's generated index.xml file for RSS sources the image to the link I put in my content file (img/picture.png) which never exists.  And so images are broken in the RSS feed. 

Is there a way for me to make the index.xml use img/high/picture.png whenever I put img/picture.png in my blog post files?

Perhaps another solution is making the progressive loader look in img/ instead of img/high/ for the high resolution images? That way I can put all the high resolution pictures in img/ and the RSS feed will find them. The low resolution files will still be in img/low/ and the progressive loader can still use those. 

I don't fully understand how the progressive loader or Hugo's XML generator work so I'm sorry if my suggestions don't make sense.

**Comment by keanemind** [comment]
For example, in [your website's XML file](https://kodewolf.com/index.xml) is this:
`<p><img src="../../images/ampli.jpg" alt="Old amplifier" /></p>`
However, the actual location of your image is https://kodewolf.com/images/high/ampli.jpg

So if you look on this RSS reader, http://www.feedbucket.com/?src=https%3A%2F%2Fkodewolf.com%2Findex.xml all the images are broken. 

Also, I'm not sure if this is related, but what is the purpose of putting the "../../" before your image filepaths?

**Comment by fuegoio** [comment]
Hi ! Thanks you for the issue, I never saw this.

> Perhaps another solution is making the progressive loader look in img/ instead of img/high/ for the high resolution images? That way I can put all the high resolution pictures in img/ and the RSS feed will find them. The low resolution files will still be in img/low/ and the progressive loader can still use those.

I think this is the best solution too, and this way there are less differences between with and without the progressive images enabled.

> Also, I'm not sure if this is related, but what is the purpose of putting the "../../" before your image filepaths?

This is still a big issue for me. Before this changement, there was a `<base>` tag in the HTML indicating the base of the site. This was useful because a call to `/img/test.png` would have called the http://test.com/img/test.png, and even if it was in a sub folder on the site like http://test.com/my-blog/img/test.png.

However, according to an issue, it prevented anchor links in the same page, like footnotes for example. So I removed it, but now you need to specify **relative** paths if your blog is in a subfolder. I don't know how to make the best of those two problems :/

**Comment by fuegoio** [comment]
So I fixed everything I think with the new version, and especially with the commit 424119cbb02a9bb660fb333213181a0c40a66b1f !
