### ISSUE TITLE
Analytics Support

### ISSUE THREAD

**Issue by mtn** [mtn/cocoa-eh-hugo-theme#23]
Hi (again)!

I added analytics support to my forked version of the theme which only involved the addition of a few (3) lines. Would you be open to adding this to the repository, along with a short explanation of setup for users? I'm happy to make the change. 😄

**Comment by fuegoio** [comment]
Hi !

Are you talking about google analytics ? I'm not so enthusiastic to implement them because I find their javascript really big and long to load, and I want to keep a lightweight version for an instant loading blog.

If you have arguments for analytics and a way to enable/disable it without disrupting the way the theme is working right now, I will be happy to add it !

Thanks you !

**Comment by mtn** [comment]
Yes to google analytics. I don't know how much "heavier" conditional Hugo statements make the site, but on my fork I currently add the script conditionally if a "googleanalytics" parameter is set. So  all the end-user has to do is add something like: `googleanalytics="UA-123-45"` to their config parameters. In footer scripts, I added an "isset" check to load the script, which doesn't need to be fully copied into the theme since it's neatly enabled internally.

Again, I'm pretty unfamiliar with the overhead of these sorts of checks, but I assume it doesn't matter in the rendered product because the analytics script would just be totally absent if the user doesn't use it. So the experience shouldn't change, if I'm correct. :dromedary_camel:

**Comment by fuegoio** [comment]
Okey let's do it ! I will see the load on client side for tests purposes. I kind of don't like the way I send users infos to Google, but this is a choice of every blog owner.

If you can do a pull request I will test it ! Thanks !
