### ISSUE TITLE
``githubRepo`` points to master branch

### ISSUE THREAD

**Issue by tobiasraabe** [mtn/cocoa-eh-hugo-theme#81]
Hey,

thanks for your theme. I am a very happy user :).

What about changing ``https://github.com/{{ .Site.Params.githubRepo }}/tree/master/content`` to ``https://github.com/{{ .Site.Params.githubRepo }}/content`` so that one can decide within the ``config.toml`` on which branch the source files are located. 

https://github.com/mtn/cocoa-eh-hugo-theme/blob/b03f2d71fe876f32c6b73753f357dbfd39aacd89/layouts/partials/footer.html#L6 

Best

**Comment by mtn** [comment]
The idea being that if the default branch is different from master, just by including the repository as normal, you end up on that branch right (and also, if someone wants to be hacky, they can specify the full path to a non-default branch), right?

Sounds good to me. If you want to make a pull request, I'd appreciate it. Otherwise, I'll make this change shortly when I get a chance. 🎈

**Comment by mtn** [comment]
Handled by #83. Thanks @tobiasraabe!
